name: Windows RDP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 350

    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v4
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: Enable RDP
        shell: powershell
        run: |
          Set-ItemProperty `
            -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' `
            -Name 'fDenyTSConnections' `
            -Value 0

          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

          Set-ItemProperty `
            -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
            -Name 'UserAuthentication' `
            -Value 1

      - name: Set RDP Password
        shell: powershell
        env:
          RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
        run: |
          $SecurePassword = ConvertTo-SecureString `
            $Env:RDP_PASSWORD `
            -AsPlainText `
            -Force

          Set-LocalUser `
            -Name "runneradmin" `
            -Password $SecurePassword

      - name: Show Tailscale IP
        shell: powershell
        run: |
          Write-Host ""
          Write-Host "==============================="
          Write-Host "TAILSCALE STATUS:"
          tailscale status
          Write-Host ""
          Write-Host "RDP IP:"
          tailscale ip -4
          Write-Host ""
          Write-Host "USERNAME: runneradmin"
          Write-Host "==============================="

      - name: Keep Alive
        shell: powershell
        run: |
          while ($true) {
            Start-Sleep -Seconds 300
          }
